"""Add student/course tables and add is_admin field into user table

Revision ID: d430ea5e5fc4
Revises: 1ddaa1d3a0b7
Create Date: 2025-03-05 16:57:03.078113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd430ea5e5fc4'
down_revision = '1ddaa1d3a0b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
